# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  N3rdNEAT_config = debug
endif
ifeq ($(config),release)
  N3rdNEAT_config = release
endif

PROJECTS := N3rdNEAT

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

N3rdNEAT:
ifneq (,$(N3rdNEAT_config))
	@echo "==== Building N3rdNEAT ($(N3rdNEAT_config)) ===="
	@${MAKE} --no-print-directory -C . -f N3rdNEAT.make config=$(N3rdNEAT_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f N3rdNEAT.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   N3rdNEAT"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"